---
title: "Plotly tutorial"
format:  
  revealjs:
    slide-number: true
    theme: theme/dsfe_theme.scss
    code-copy: false
    output-location: column
    code-line-numbers: false
revealjs-plugins:
  - detective
jupyter: python3
highlight-style: "dracula"
brand: brand/_dsfe_brand.yml
execute:
  echo: true
---

## A simple bar plot

```{python}
import plotly.express as px
```

## A simple bar plot

```{python}
import plotly.express as px

days = ["Mon", "Tue", "Wed"]
sleep_hours = [8, 5, 10]
```

## A simple bar plot

```{python}
#| eval: false
import plotly.express as px

days = ["Mon", "Tue", "Wed"]
sleep_hours = [8, 5, 10]

fig = px.bar(


)
```

## A simple bar plot

```{python}
#| eval: false
import plotly.express as px

days = ["Mon", "Tue", "Wed"]
sleep_hours = [8, 5, 10]

fig = px.bar(
  x = days, 
  y = sleep_hours
)
```

## A simple bar plot

```{python}
import plotly.express as px

days = ["Mon", "Tue", "Wed"]
sleep_hours = [8, 5, 10]

fig = px.bar(
  x = days, 
  y = sleep_hours
)
fig.show()
```

## Adding a title

:::{.detective data-detective-search="title"}
```{python}
import plotly.express as px

days = ["Mon", "Tue", "Wed"]
sleep_hours = [8, 5, 10]

fig = px.bar(
  x = days, 
  y = sleep_hours, 
  title = "Hours of sleep"
)
fig.show()
```
:::

## A `pandas` dataframe

:::{.detective data-detective-search="DataFrame"}
```{python}
#| eval: false
import pandas as pd

sleep = pd.DataFrame({
  

})
```
:::

## A `pandas` dataframe

:::{.detective data-detective-search="DataFrame"}
```{python}
#| eval: false
import pandas as pd

sleep = pd.DataFrame({
  "day": ["Mon", "Tue", "Wed"],
  "sleep_hours": [8, 5, 10]
})
```
:::


## A `pandas` dataframe

:::{.detective data-detective-search="data_frame"}
```{python}
import pandas as pd

sleep = pd.DataFrame({
  "day": ["Mon", "Tue", "Wed"],
  "sleep_hours": [8, 5, 10]
})

fig = px.bar(
  data_frame = sleep,
  x = days, 
  y = sleep_hours, 
  title = "Hours of sleep"
)
fig.show()
```
:::


## A histogram

:::{.detective data-detective-search="read_csv"}
```{python}
#| eval: false
iris = pd.read_csv("data/iris.csv")
```
:::

## A histogram

:::{.detective data-detective-search="histogram"}
```{python}
iris = pd.read_csv("data/iris.csv")

fig = px.histogram(
  data_frame = iris,
  x = "Petal.Length",
)
fig.show()
```
:::


## Adjusting bin size

:::{.detective data-detective-search="nbins"}
```{python}
iris = pd.read_csv("data/iris.csv")

fig = px.histogram(
  data_frame = iris,
  x = "Petal.Length", 
  nbins = 10
)
fig.show()
```
:::

## Adjusting bin size

:::{.detective data-detective-search="nbins, 20"}
```{python}
iris = pd.read_csv("data/iris.csv")

fig = px.histogram(
  data_frame = iris,
  x = "Petal.Length", 
  nbins = 20
)
fig.show()
```
:::

## Box plots

Explain box plots

## Box plots

:::{.detective data-detective-search="box"}
```{python}
fig = px.box(
  data_frame = iris,
  y = "Petal.Length",
)
fig.show()
```
:::

## Adding points with boxplot

:::{.detective data-detective-search="points"}
```{python}
fig = px.box(
  data_frame = iris,
  y = "Petal.Length",
  points="all"
)
fig.show()
```
:::

## Adjust hover data

:::{.detective data-detective-search="hover_data"}
```{python}
fig = px.box(
  data_frame = iris,
  y = "Petal.Length",
  points="all",
  hover_data=["Species"]
)
fig.show()
```
:::

## Boxplots

:::{.detective data-detective-search="x, Species"}
```{python}
fig = px.box(
  data_frame = iris,
  x = "Species",
  y = "Petal.Length"
)
fig.show()
```
:::

## Adding color scales

```{python}
#| echo: false

sleep = pd.DataFrame({
  "day": days,
  "sleep_hours": sleep_hours
})
```

:::{.detective data-detective-search="color"}
```{python}
fig = px.bar(
  data_frame = sleep,
  x = "day", 
  y = "sleep_hours", 
  color = "day"
)
fig.show()
```
:::

## Customize color scales

:::{.detective data-detective-search="color_discrete_map"}
```{python}
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color_discrete_map={
    "Mon": "rgb(0, 0, 255)",
    "Tue": "rgb(0, 255,0)",
    "Wed": "rgb(255, 0, 0)"
  },
  color = "day"
)
fig.show()
```
:::

## Customize color scales

:::{.detective data-detective-search="my_colors"}
```{python}
my_colors = {
    "Mon": "rgb(0, 0, 255)",
    "Tue": "rgb(0, 255,0)",
    "Wed": "rgb(255, 0, 0)"
  }
```
:::

## Customize color scales

:::{.detective data-detective-search="color_discrete_map, my_colors"}
```{python}
my_colors = {
    "Mon": "rgb(0, 0, 255)",
    "Tue": "rgb(0, 255,0)",
    "Wed": "rgb(255, 0, 0)"
  }
fig = px.box(
  data_frame=px.data.iris(),
  x = "species",
  y = "petal_length",
  title = "Hours of sleep",
  color_discrete_map=my_colors,
  color = "species"
)
fig.show()
```
:::

## Preset colors {.smaller}

:::{.detective data-detective-search="inferno"}
```{python}
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color_continuous_scale = "inferno",
  color = "sleep_hours"
)
fig.show()
```
:::

## Customize color scales {.smaller}

:::{.detective data-detective-search="custom_color"}
```{python}
custom_color = [
  ("rgb(0, 0, 255)"),
  ("rgb(0, 255,0)"),
  ("rgb(255, 0, 0)")
]
```
:::

## Customize color scales {.smaller}

:::{.detective data-detective-search="custom_color"}
```{python}
custom_color = [
  ("rgb(0, 0, 255)"),
  ("rgb(0, 255,0)"),
  ("rgb(255, 0, 0)")
]
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color_continuous_scale = custom_color,
  color = "sleep_hours"
)
fig.show()
```
:::

## Scatter plots

:::{.detective data-detective-search="scatter"}
```{python}
fig = px.scatter(
  data_frame = iris,
  x = "Sepal.Length",
  y = "Petal.Length"
)
fig.show()
```
:::

## Symbols

:::{.detective data-detective-search="symbol"}
```{python}
fig = px.scatter(
  data_frame = iris,
  x = "Sepal.Length",
  y = "Petal.Length",
  symbol="Species"
)
fig.show()
```
:::

## Adding colors with symbols

:::{.detective data-detective-search="symbol, color"}
```{python}
fig = px.scatter(
  data_frame = iris,
  x = "Sepal.Length",
  y = "Petal.Length",
  symbol="Species",
  color="Species"
)
fig.show()
```
:::

## Scatter plot with trendline

:::{.detective data-detective-search="trendline, ols"}
```{python}
fig = px.scatter(
  data_frame = iris,
  x = "Sepal.Length",
  y = "Petal.Length",
  symbol="Species",
  color="Species",
  trendline = "ols"
)
fig.show()
```
:::

## Line plot

:::{.detective data-detective-search="line"}
```{python}
stocks = pd.read_csv("data/stocks.csv")

fig = px.line(
  data_frame = stocks,
  x = "Date",
  y = "MSFT"
)
fig.show()
```
:::

## Correlation plot

:::{.detective data-detective-search="drop"}
```{python}
#| eval: false
#| output-location: default
# Remove species column from iris dataset
iris_2 = iris.drop("Species", axis = 1)
```
:::

## Correlation plot

:::{.detective data-detective-search="corr"}
```{python}
#| output-location: default
# Remove species column from iris dataset
iris_2 = iris.drop("Species", axis = 1)

iris_corr = iris_2.corr(method="pearson")

print(iris_corr)
```
:::

## Correlation plot

:::{.detective data-detective-search="imshow"}
```{python}
fig = px.imshow(
  iris_corr,
)
fig.show()
```
:::

## Correlation plot

:::{.detective data-detective-search="text_auto"}
```{python}
fig = px.imshow(
  iris_corr,
  text_auto=True,
)
fig.show()
```
:::

## Correlation plot

:::{.detective data-detective-search="color_continuous_scale"}
```{python}
fig = px.imshow(
  iris_corr,
  text_auto=True,
  color_continuous_scale="RdYlGn"
)
fig.show()
```
:::

## Correlation plot

:::{.detective data-detective-search="zmin, zmax"}
```{python}
fig = px.imshow(
  iris_corr,
  text_auto=True,
  color_continuous_scale="RdYlGn",
  zmin = -1, zmax = 1
)
fig.show()
```
:::

## Hover information

```{python}
fig = px.scatter(
  data_frame = iris,
  x = "Sepal.Length",
  y = "Petal.Length"
)
fig.show()
```

## Hover information

:::{.detective data-detective-search="hover_data"}
```{python}
fig = px.scatter(
  data_frame = iris,
  x = "Sepal.Length",
  y = "Petal.Length",
  hover_data=["Species"]
)
fig.show()
```
:::

## Customize hover information

:::{.detective data-detective-search="update_layout"}
```{python}
fig = px.scatter(
  data_frame = iris,
  x = "Sepal.Length",
  y = "Petal.Length",
  hover_data=["Species"]
)

fig.update_layout(



)
fig.show()
```
:::

## Customize hover information

:::{.detective data-detective-search="hoverlabel"}
```{python}
fig = px.scatter(
  data_frame = iris,
  x = "Sepal.Length",
  y = "Petal.Length",
  hover_data=["Species"]
)

fig.update_layout(
  hoverlabel=dict(
    bgcolor="white",
    font_size=16,
    font_family="Rockwell"
  )
)
fig.show()
```
:::

## Plot legend

```{python}
fig = px.scatter(
  data_frame = iris,
  x = "Sepal.Length",
  y = "Petal.Length",
  symbol="Species",
  color="Species"
)
fig.show()
```

## Style plot legend

:::{.detective data-detective-search="my_legend"}
```{python}
my_legend = dict(
  x=0.2,
  y=0.95, 
  bgcolor="rgb(240, 229, 111)"
)
```
:::

## Style plot legend

:::{.detective data-detective-search="showlegend, legend"}
```{python}
my_legend = dict(
  x=0.2,
  y=0.95, 
  bgcolor="rgb(240, 229, 111)"
)

fig.update_layout(
  showlegend=True, 
  legend=my_legend
)
fig.show()
```
:::

## Annotations

```{python}
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color = "day"
)
```

## Annotations

:::{.detective data-detective-search="less, showarrow, arrowhead"}
```{python}
less = dict(
    x="Tue", y=5, 
    text="Less sleep",
    font=dict(color="black"), 
    showarrow=True, arrowhead=4
)
```
:::

## Annotations {.smaller}

:::{.detective data-detective-search="annotations"}
```{python}
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color = "day"
)

fig.update_layout(annotations=[less])

fig.show()
```
:::

## Multiple annotations

:::{.detective data-detective-search="more"}
```{python}
less = dict(
    x="Tue", y=5, 
    text="Less sleep",
    font=dict(color="black"), 
    showarrow=True, arrowhead=4
)

# Create the second annotation
more = dict(
    x="Wed", y=10, 
    text="More sleep",
    font=dict(color="black"), 
    showarrow=True, arrowhead=4,
)
```
:::

## Annotations {.smaller}

:::{.detective data-detective-search="less, more"}
```{python}
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color = "day"
)

fig.update_layout(annotations=[less, more])

fig.show()
```
:::

## Annotations

:::{.detective data-detective-search="text, showarrow"}
```{python}
h_sleep = 8
msg = dict(
  x="Tue", y=9,
  text=f"Mon: {h_sleep} hours",
  font=dict(
    size=20, 
    color="white"
  ),
  bgcolor="rgb(237, 64, 200)", 
  showarrow=False
)
```
:::

## Annotations {.smaller}

:::{.detective data-detective-search="annotations"}
```{python}
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color = "day"
)

fig.update_layout(annotations = [msg])

fig.show()
```
:::

## Annotations

:::{.detective data-detective-search="xref, yref"}
```{python}
h_sleep = 8
msg = dict(
  x=0.05, y=0.9, 
  xref="paper", yref="paper",
  text=f"Mon: {h_sleep} hours",
  font=dict(
    size=20, 
    color="white"
  ),
  bgcolor="rgb(237, 64, 200)", 
  showarrow=False
)
```
:::

## Annotations {.smaller}

```{python}
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color = "day"
)

fig.update_layout(annotations = [msg])

fig.show()
```

## Axis labels {.smaller}

:::{.detective data-detective-search="update_xaxes, update_yaxes"}
```{python}
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color = "day"
)

fig.update_xaxes(title_text="Day")
fig.update_yaxes(title_text="Time (hours)")

fig.show()
```
:::

## Axis labels {.smaller}

:::{.detective data-detective-search="update_layout, xaxis, yaxis"}
```{python}
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color = "day"
)

fig.update_layout(dict(
  xaxis=dict(title = dict(text="Day")),
  yaxis=dict(title = dict(text="Time (hours)"))
))

fig.show()
```
:::

## Axis labels {.smaller}

:::{.detective data-detective-search="title, range"}
```{python}
fig = px.bar(
  data_frame=sleep,
  x = "day", 
  y = "sleep_hours", 
  title = "Hours of sleep",
  color = "day"
)

fig.update_layout(dict(
  xaxis=dict(title = dict(text="Day")),
  yaxis=dict(
    title = dict(text="Time (hours)"),
    range = [4, 15]
  )
 )
)

fig.show()
```
:::

## Axis transformation

:::{.detective data-detective-search="log_y"}
```{python}
fig = px.scatter(
  data_frame = iris,
  x = "Sepal.Length",
  y = "Petal.Length",
  color="Species",
  log_y= True
)

fig.show()
```
:::

# Subplots

## Subplots {.smaller}

:::{.detective data-detective-search="plotly.subplots, make_subplots"}
```{python}
import plotly.express as px
from plotly.subplots import make_subplots
```
:::

## Subplots {.smaller}

```{python}
import plotly.express as px
from plotly.subplots import make_subplots

fig = make_subplots(rows=2, cols=1)
```

## Subplots {.smaller}

:::{.detective data-detective-search="histogram, box"}
```{python}
import plotly.express as px
from plotly.subplots import make_subplots

fig = make_subplots(rows=2, cols=1)

hist = px.histogram(
  data_frame = iris, x='Petal.Length'
)

box = px.box(
 data_frame = iris, x='Petal.Length'
)
```
:::

## Subplots {.smaller}

:::{.detective data-detective-search="add_trace"}
```{python}
import plotly.express as px
from plotly.subplots import make_subplots

fig = make_subplots(rows=2, cols=1)

hist = px.histogram(
  data_frame = iris, x='Petal.Length'
)

box = px.box(
 data_frame = iris, x='Petal.Length'
)

fig.add_trace(hist.data[0], row=1, col=1)
fig.add_trace(box.data[0], row=2, col=1)

fig.show()
```
:::

## Stacked subplots {.smaller}

```{python}
fig = make_subplots(
    rows=3, cols=1,
    subplot_titles=\
      ['Setosa', 'Versicolor', 'Virginica']
)

row_num = 1

for species in\
   ['setosa', 'versicolor', 'virginica']:
    df = iris[iris['Species'] == species]
    scatter = px.scatter(
      df, x='Petal.Length', y='Sepal.Length'
    )
    fig.add_trace(
      scatter.data[0], 
      row=row_num, 
      col=1
    )
    row_num += 1

fig.show()
```

## Shared axes {.smaller}

:::{.detective data-detective-search="shared_xaxes"}
```{python}
fig = make_subplots(
    rows=3, cols=1,
    subplot_titles=\
      ['Setosa', 'Versicolor', 'Virginica'],
    shared_xaxes=True
)

row_num = 1

for species in\
   ['setosa', 'versicolor', 'virginica']:
    df = iris[iris['Species'] == species]
    scatter = px.scatter(
      df, x='Petal.Length', y='Sepal.Length'
    )
    fig.add_trace(
      scatter.data[0], 
      row=row_num, 
      col=1
    )
    row_num += 1

fig.show()
```
:::

# Layering plots {.smaller}

```{python}
from plotly.graph_objects import Figure

weather = pd.read_csv("data/weather.csv")

scatter_fig = px.scatter(
  weather, 
  x='DATE', y='Boston'
)

line_fig = px.line(
  weather, 
  x='DATE', y='Houston',
  color_discrete_sequence=['green']
)

combined_fig = Figure(data=[*scatter_fig.data, *line_fig.data])
combined_fig.update_layout(title='USA city temperatures')
combined_fig.show()
```

# Adding more layers {.smaller}

```{python}
line_fig_seattle = px.line(
  weather, 
  x='DATE', y='Seattle',
  color_discrete_sequence=['orange']
)

combined_fig.add_trace(line_fig_seattle.data[0])
combined_fig.update_layout(title='USA city temperatures')
combined_fig.show()
```